export const myFun = x => x*x

export const tError = () => {
	throw new Error('test')
}
